### ISSUE TITLE
Falta de contador de intentos cuando reintentas el juego

### ISSUE THREAD

**Issue by frankcdlc** [MoisesAtay/trivia1#4]
Cuando deseas jugar nuevamente, debería tener un contador de los intentos que vas hasta el momento

![imagen](https://user-images.githubusercontent.com/59923535/190836014-0ba08172-2c3e-4ae1-be00-6e8e8aa897c4.png)

**Comment by MoisesAtay** [comment]
gracias por la recomendación, lo implementaré
